export const NEWS_712_ADDITIONAL_MESSAGES = [
  "Lola ha nazionalizzato l’ombra. I cittadini potranno ripararsi gratuitamente dalle dodici alle quattordici.",
  "Roger ha perso una causa contro un distributore automatico. Il giudice ha ritenuto credibile la versione della merendina.",
  "Bugs ha scoperto un pianeta quadrato. Le spedizioni precedenti si erano fermate agli angoli.",
  "Tippete è stato rapito dagli alieni. Lo hanno riportato con una lettera di accompagnamento.",
  "Quick ha superato il limite di velocità in una fotografia.",
  "Palla di Neve ha acquistato il Polo Sud. Il nord della proprietà resta da definire.",
  "Tappo ha introdotto il pedaggio sulle scale di casa. La discesa è gratuita solo entro quindici minuti.",
  "Bianconiglio ha trovato una ricevuta del prossimo anno. È già pentito dell’acquisto.",
  "Lola ha imposto il saluto militare alle porte automatiche. Due supermercati risultano in stato di insubordinazione.",
  "Roger ha scoperto un tesoro sepolto. Era il fondo pensione di un pirata ancora in attività.",
  "Bugs ha insegnato a un tostapane a provare emozioni. Ora brucia il pane per ripicca.",
  "Tippete ha adottato un cespuglio che lo segue ovunque. Il vivaio esclude la restituzione per motivi affettivi.",
  "Quick è arrivato primo a un appuntamento al buio. Non erano previste altre posizioni.",
  "Palla di Neve ha spostato una collina per migliorare il segnale. L’altra provincia ora vede solo televendite.",
  "Tappo ha aperto un outlet di miracoli. Disponibili soprattutto guarigioni da piccoli fastidi.",
  "Bianconiglio ha dato buca a un incontro già avvenuto. I presenti stanno scomparendo dalle foto.",
  "Lola ha sostituito il consiglio comunale con otto sedie. Il bilancio è stato approvato senza obiezioni.",
  "Roger ha trovato il senso della vita sotto il sedile. Lo ha perso durante la pulizia dell’auto.",
  "Bugs ha brevettato un cuscino che risponde alle preoccupazioni. La risposta standard è «domani».",
  "Tippete ha aperto un allevamento di unicorni. L’ASL contesta l’assenza di protezioni sulle punte.",
  "Quick ha finito una coda prima di mettersi in fila.",
  "Palla di Neve ha importato sabbia lunare. Il gatto l’ha già valutata positivamente.",
  "Tappo vende posti in prima fila durante le liti condominiali.",
  "Bianconiglio ha incontrato il proprio io maturo. Non si sono riconosciuti.",
  "Lola ha acquistato una costellazione per scriverci il proprio nome. Gli astronomi chiedono almeno il rispetto delle distanze.",
  "Roger ha restituito una sfera di cristallo. Mostrava soltanto rate.",
  "Bugs ha costruito un drone per controllare altri droni. Nessuno controlla più il parcheggio.",
  "Tippete è stato nominato direttore del nulla. Chiede più personale.",
  "Quick ha fatto una partenza intelligente. È rimasto a casa e ha spento il telefono.",
  "Palla di Neve ha congelato una discussione. Il litigio riprenderà dopo lo scongelamento.",
  "Tappo ha aperto una biblioteca di scuse. Quella del traffico non è più disponibile.",
  "Bianconiglio ha annullato il proprio compleanno. L’età è aumentata d’ufficio.",
  "Lola ha introdotto la monarchia a rotazione. Roger regnerà dopo aver sparecchiato.",
  "Roger ha scoperto una botola nel cielo. Per aprirla serve una scala che nessuno vuole prestare.",
  "Bugs ha inventato una sveglia che si sente in colpa. Da tre giorni non suona.",
  "Tippete ha denunciato un mago per averlo segato a metà senza indicare i tempi di riconsegna.",
  "Quick ha anticipato un temporale. È arrivato bagnato prima della pioggia.",
  "Palla di Neve ha aperto una pista di pattinaggio in pendenza. Il ritorno è a carico del cliente.",
  "Tappo ha messo a reddito un sogno ricorrente. Ora compare una pubblicità prima della caduta.",
  "Bianconiglio è stato bocciato in storia per aver citato fatti non ancora approvati.",
  "Lola ha inaugurato una statua di se stesso provvisoria. Quella definitiva avrà un’espressione più modesta.",
  "Roger ha pescato un messaggio d’aiuto. Lo ha rimesso in acqua perché troppo piccolo.",
  "Bugs ha collegato il frigorifero al mercato azionario. Il latte sta rendendo più del previsto.",
  "Tippete ha comprato un tappeto volante. Non può decollare finché il gatto dorme sopra.",
  "Quick ha attraversato una galassia con il serbatoio in riserva.",
  "Palla di Neve ha ottenuto l’affidamento di una valanga. Dovrà portarla fuori due volte al giorno.",
  "Tappo ha aperto un centro scommesse sulle decisioni di Roger. Il banco sospetta partite truccate.",
  "Bianconiglio ha dimenticato qualcosa nel Rinascimento. Tornerà quando ci sarà meno gente.",
  "Lola ha dichiarato festivo il giorno in cui gli è passata la voglia.",
  "Roger ha fatto amicizia con un predatore alieno. La specie lo considera ancora un aperitivo.",
  "Bugs ha inventato un ventilatore che sposta direttamente l’estate.",
  "Tippete è rimasto chiuso fuori dalla propria immaginazione. Aspetta il fabbro.",
  "Quick ha vinto una gara a eliminazione eliminando la gara.",
  "Palla di Neve ha preso il Sole in leasing. Prevista una maxi rata al tramonto.",
  "Tappo affitta alibi ammobiliati. Le testimonianze sono escluse.",
  "Bianconiglio ha aperto una mail del futuro. Era comunque spam.",
  "Lola ha sostituito le tasse con regali obbligatori. Il gettito è aumentato, ma mancano i bigliettini.",
  "Roger ha comprato un verme spaziale pensando fosse un tubo. Il giardino ora comunica con Saturno.",
  "Bugs ha scoperto che i buchi neri hanno il fondo. Dentro ci sono soprattutto accendini.",
  "Tippete ha partecipato a una spedizione scientifica per errore. Credeva che «campo base» fosse il nome del locale.",
  "Quick ha ridotto il viaggio a zero minuti. La compagnia mantiene il supplemento bagaglio.",
  "Palla di Neve ha portato un ghiacciaio al mare. Le autorità parlano di una scelta educativa discutibile.",
  "Tappo ha aperto un banco dei pegni per ricordi. I primi baci vengono valutati dopo la verifica della controparte.",
  "Bianconiglio ha invitato a cena il proprio futuro. Ha disdetto per imbarazzo.",
  "Lola ha ordinato un censimento dei pensieri ostili. Roger dovrà compilare un allegato.",
  "Roger è stato risucchiato da una pubblicità. Per liberarlo mancano cinque secondi e una crocetta abbastanza grande.",
  "Bugs ha creato un navigatore per scelte sentimentali. Al primo utilizzo ha suggerito di tornare indietro.",
  "Tippete ha ricevuto una bolletta per l’energia negativa. Contesta la lettura.",
  "Quick ha brevettato un semaforo giallo più convincente.",
  "Palla di Neve ha perso una nuvola al supermercato. Piove nel reparto surgelati.",
  "Tappo ha iniziato a vendere finali alternativi per discussioni. Roger ha ordinato quello in cui ha ragione.",
  "Bianconiglio ha scoperto che il prossimo anno è già prenotato.",
  "Lola ha aperto un’ambasciata nella roulotte di Tappo. I rapporti sono tesi per l’uso del frigo.",
  "Roger ha acquistato una miniera di sale. La usa per correggere una singola grigliata.",
  "Bugs ha inventato un detector di persone che dicono «io lo sapevo». Il dispositivo suona anche da spento.",
  "Tippete ha ottenuto il permesso di costruire una casa sull’albero genealogico. I parenti contestano la veranda.",
  "Quick ha attraversato il tempo senza biglietto. Il controllore lo aspetta all’infanzia.",
  "Palla di Neve ha fatto nevicare in salotto. Il divano è aperto agli impianti dalle otto.",
  "Tappo ha aperto un servizio di catering per rituali occulti. Disponibile l’opzione vegetariana.",
  "Bianconiglio ha spostato una scadenza così avanti da incontrarla nella vita successiva.",
  "Lola ha vietato il brutto tempo durante le inaugurazioni. La pioggia è stata invitata a manifestare altrove.",
  "Roger ha chiesto una seconda opinione allo specchio. Anche quello del bagno ha confermato.",
  "Bugs ha scoperto l’origine dell’eco. È Tippete, che ripete senza capire.",
  "Tippete ha comprato una stazione spaziale con formula bed and breakfast. L’ossigeno è disponibile al bar.",
  "Quick ha iniziato il giro di prova ed è rientrato sposato.",
  "Palla di Neve ha trasferito il mare in un contenitore più comodo.",
  "Tappo ha brevettato una serratura che riconosce chi viene solo per chiedere favori.",
  "Bianconiglio ha ricevuto le scuse di domani. Preferirebbe sapere per cosa.",
  "Lola è stato nominato giudice in un universo senza leggi. Le sentenze dipenderanno dall’umore.",
  "Roger ha aperto una porta proibita. Dietro c’era l’amministratore che aspettava le quote.",
  "Bugs ha costruito un robot per bere il caffè con lui. Il robot ha chiesto di non parlare prima.",
  "Tippete ha investito in una startup che produce terra piatta pieghevole.",
  "Quick ha fatto così presto da dover attendere l’inizio della propria fretta.",
  "Palla di Neve ha acquistato un tifone ricondizionato. Il venditore garantisce soltanto i primi tre tetti.",
  "Tappo ha introdotto un costo di attivazione per le amicizie.",
  "Bianconiglio ha recuperato un pomeriggio perso. Era ancora sul divano.",
  "Lola ha installato una campana che suona quando qualcuno gli dà ragione. La collauderanno i tecnici.",
  "Roger ha trovato un alieno nel motore. Sostiene di essere lì per la revisione.",
  "Bugs ha insegnato alle piante a lamentarsi della sete. I balconi risultano più rumorosi delle assemblee.",
  "Tippete ha aperto un negozio che vende soltanto l’ultima cosa che cerchi.",
  "Quick ha portato avanti l’orologio e ricevuto una multa per traino non autorizzato.",
  "Palla di Neve ha brevettato una pioggia che evita gli occhiali.",
  "Tappo ha messo in vendita l’esperienza completa del campeggio. Include una pietra sotto il materasso.",
  "Bianconiglio ha comprato del tempo libero. Gli è arrivato durante l’orario di lavoro.",
  "Lola ha nominato un ministro incaricato di rispondere «vediamo». Le altre competenze verranno definite.",
  "Roger è stato riconosciuto da un animale estinto. Gli scienziati chiedono spiegazioni a entrambi.",
  "Bugs ha ricreato il suono del Big Bang. I vicini sostengono fosse fuori fascia oraria.",
  "Tippete ha trovato un passaggio verso un mondo migliore. È chiuso per inventario.",
  "Quick ha superato il limite di velocità sul tapis roulant. La palestra gli ha ritirato le scarpe.",
  "Palla di Neve ha avviato una raccolta differenziata delle intemperie.",
  "Tappo ha aperto un parcheggio per astronavi. Il primo cliente occupa sei posti e sostiene di restare poco.",
  "Bianconiglio ha trovato il proprio numero tra le chiamate perse del 1984.",
  "Lola ha ceduto parte della sovranità in cambio di una piazzola all’ombra.",
  "Roger ha chiesto a un genio di renderlo irresistibile. Da allora attira soltanto calamite.",
  "Bugs ha inventato una griglia che certifica chi ha fatto davvero il lavoro.",
  "Tippete ha aperto un’agenzia di casting per comparse nei sogni. Cercasi insegnante del liceo, preferibilmente minaccioso.",
  "Quick ha imboccato una scorciatoia ed è arrivato a una versione precedente del bar.",
  "Palla di Neve ha chiesto di spostare l’asse terrestre. Gli dava fastidio mentre stendeva.",
  "Tappo ha applicato le spese di gestione a un prestito di venti euro.",
  "Bianconiglio ha accidentalmente risposto a una domanda che Roger farà tra undici anni.",
  "Lola ha dichiarato ufficiale il proprio dialetto. I traduttori chiedono una settimana per «quella roba lì».",
  "Roger ha portato un sasso lunare a casa. Di notte tenta di tornare in orbita.",
  "Bugs ha creato un’intelligenza artificiale che dice quando smettere di lavorare. È stata licenziata durante la presentazione.",
  "Tippete ha scoperto che il suo riflesso esce quando lui dorme.",
  "Quick ha fatto un pit stop durante una passeggiata.",
  "Palla di Neve ha aperto un deposito bagagli per comete.",
  "Tappo ha comprato il brevetto della fortuna. Gli utilizzi precedenti verranno fatturati retroattivamente.",
  "Bianconiglio ha anticipato una figuraccia per liberare il fine settimana.",
  "Lola ha istituito la giornata nazionale del «non oggi». Tutte le celebrazioni sono state rinviate.",
  "Roger ha ordinato una birra in una dimensione liquida. Il cameriere gli ha chiesto di uscire dal bicchiere.",
  "Bugs ha scoperto una galassia che ruota al contrario. Il produttore consiglia di spegnerla e riaccenderla.",
  "Tippete ha aperto un negozio di porte dimensionali. Le uscite di sicurezza portano tutte nel magazzino.",
  "Quick è stato fotografato in due luoghi contemporaneamente. In entrambi cercava parcheggio.",
  "Palla di Neve ha acquistato un’estate del 1996. Dice che quella nuova non scalda allo stesso modo.",
  "Tappo ha introdotto il supplemento sincerità nei complimenti.",
  "Bianconiglio ha mandato il proprio passato a prendersi una pausa. Ora non ricorda le medie.",
  "Lola ha fatto installare il pulsante «salta introduzione» durante le cerimonie pubbliche.",
  "Roger è finito in un universo dove nessuno mente. È rimasto il tempo di chiedere come stava.",
  "Bugs ha aperto un laboratorio per verificare se «basta soffiare» sia una tecnica medica o informatica.",
  "Tippete ha affittato una casa delle bambole. La metratura dell’annuncio era in scala.",
  "Quick ha tentato di abbreviare l’attesa chiamandola diversamente.",
  "Palla di Neve ha trascinato una nuvola sopra l’auto per non pagare il lavaggio.",
  "Tappo ha fondato una società che certifica l’ultima birra. Nessuna pratica è stata chiusa.",
  "Bianconiglio ha saltato i titoli di coda della giornata. Ha perso una scena importante in cucina.",
  "Lola ha promosso un referendum sulla posizione del divano. La campagna elettorale divide il soggiorno.",
  "Roger ha chiesto al destino una prova concreta. Gli è arrivato un mobile da montare.",
  "Bugs ha progettato occhiali per vedere le intenzioni. Roger appare sfocato.",
  "Tippete ha ricevuto la cittadinanza onoraria da un villaggio che non riesce a lasciare.",
  "Quick ha concluso una riunione prima che qualcuno condividesse lo schermo.",
  "Palla di Neve ha iscritto una slavina a un corso di autocontrollo.",
  "Tappo ha aperto una pensione per problemi lasciati a casa durante le ferie.",
  "Bianconiglio ha archiviato il futuro per errore. L’assistenza cerca il file.",
  "Lola ha nominato cavaliere chi ha riportato il caricatore. L’onorificenza verrà revocata se non è quello giusto.",
  "Roger ha acquistato un manuale per diventare onnisciente. Mancano le pagine dispari.",
  "Bugs ha trasmesso musica nello spazio. Una civiltà lontana ha chiesto se può mettere qualcosa di conosciuto.",
  "Tippete ha costruito un bunker contro le conversazioni imbarazzanti. Roger è già dentro.",
  "Quick ha fatto il giro del mondo per evitare un conoscente. Lo ha incontrato all’arrivo.",
  "Palla di Neve ha messo un’etichetta sul proprio iceberg. In ufficio sparivano sempre le cose dal freezer.",
  "Tappo ha inventato uno scontrino che segue chi deve ancora dividere il conto.",
  "Bianconiglio ha proposto di ripetere una serata riuscita. Tutti ricordano già di essere impegnati.",
  "Lola ha ordinato che il Sole venga abbassato di un punto. L’astronomo di corte cerca il telecomando.",
  "Roger ha comprato una pozione di saggezza. La sta conservando per un’occasione meno impegnativa.",
  "Bugs ha installato un rilevatore di bugie sulla griglia. Si attiva a ogni «manca un minuto».",
  "Tippete ha tentato di pagare in contanti in un universo teorico.",
  "Quick ha anticipato il check-in di un albergo ancora da costruire.",
  "Palla di Neve ha aperto una spiaggia riscaldata. I clienti chiedono di poter toccare la sabbia.",
  "Tappo ha noleggiato un deja-vu a tre clienti contemporaneamente.",
  "Bianconiglio ha eliminato una pessima decisione dal passato. Il gruppo ora non sa chi abbia comprato la griglia.",
  "Lola ha inaugurato un monumento al contribuente sconosciuto. Tappo sostiene di sapere chi sia.",
  "Roger ha scoperto una civiltà dietro lo zoccolo della cucina. Gli abitanti chiedono la rimozione del gatto.",
  "Bugs ha costruito una macchina per dividere il conto equamente. Si è rifiutata di procedere finché Roger non ammette il dolce.",
  "Tippete ha adottato una creatura capace di assumere qualsiasi forma. Ha scelto una sedia scomoda.",
  "Quick ha percorso l’intera Via Lattea senza incontrare un distributore aperto.",
  "Palla di Neve ha trasformato la rugiada in un servizio su prenotazione.",
  "Tappo ha aperto un negozio di ricordi mai vissuti. I clienti chiedono soprattutto estati con più soldi.",
  "Bianconiglio ha trovato un universo in cui sono tutti puntuali. È arrivato dopo la chiusura."
] as const;

