import { NEWS_712_ADDITIONAL_MESSAGES } from './notification-content-712-additional';

export const GODO_MESSAGES = [
  "Oggi ti andrà di merda. Questa notifica è la parte più bella della giornata.",
  "Il vino deve respirare. Tu intanto potresti smettere di parlare.",
  "Hai buon gusto. Peccato si manifesti solo davanti allo scaffale degli alcolici.",
  "Oggi qualcuno ti dirà che sei una bella persona. Aspetta che sia sobrio prima di emozionarti.",
  "Buongiorno. Il peggio deve ancora venire e sa dove abiti.",
  "Oggi la vita ti sorprenderà. Come una cagata senza carta.",
  "Ti aspetta una giornata piena di opportunità. Di incazzarti.",
  "Domani sarà peggio. Goditi questa merda finché è fresca.",
  "Se oggi fila tutto liscio, fatti due domande.",
  "Il destino ha qualcosa in serbo per te. Riguardati.",
  "Oggi qualcuno ti rovinerà la giornata. Non serve che cominci tu.",
  "Svegliati con un obiettivo. Arrivare a sera senza insulti è già ambizioso.",
  "Il buongiorno si vede dal mattino. Condoglianze.",
  "La fortuna sta bussando. Sicuramente hai il citofono rotto.",
  "Oggi puoi fare la differenza. In peggio, ma vale comunque.",
  "La giornata è tua. Purtroppo non si può restituire.",
  "Sorridi alla vita. Vediamo quanto ci mette a toglierti la voglia.",
  "Oggi aspettati l’inaspettato. Principalmente spese.",
  "Hai aperto gli occhi. Le rotture di coglioni hanno ricevuto la notifica.",
  "La ruota gira. Oggi ti passa sopra.",
  "Parti con il piede giusto. La merda è sotto l’altro.",
  "Oggi il karma lavora. Speriamo non trovi la tua pratica.",
  "Il sole splende per tutti. Anche sugli stronzi che incontrerai.",
  "Nessuna cattiva notizia? Forse il telefono non sta prendendo, aspetta.",
  "Oggi sarà memorabile. Conserva gli scontrini per il rimborso.",
  "Respira profondamente. Serve fiato per tutti quei sospiri.",
  "C’è luce in fondo al tunnel. Poi arriva la bolletta.",
  "Il peggio è passato. Ha detto che torna con un amico.",
  "Oggi tutto è possibile. Tranne che ti lascino in pace.",
  "Hai dormito otto ore per essere stanco con più preparazione.",
  "Nuovo giorno, nuovi problemi. Quelli vecchi fanno da tutor.",
  "Il mondo è pieno di meraviglie. Il tuo tragitto le evita accuratamente tutte.",
  "Oggi sii paziente. Gli idioti hanno dormito benissimo.",
  "Buon lavoro. Anche oggi venderai ore irripetibili della tua vita solo per poter pagare le bollete.",
  "Sei una risorsa preziosa. Infatti oggi cercheranno di spremerti fino all’ultima goccia. Auguri.",
  "La riunione durerà poco. È la prima stronzata che sentirai oggi.",
  "Oggi darai il massimo. Poi ti chiederanno perché non lo fai sempre.",
  "Riceverai una nuova email tra poco. Qualcuno ha deciso che eri troppo sereno.",
  "Oggi il tuo impegno verrà riconosciuto. Ti daranno altro lavoro.",
  "Hai finito tutto? Grave errore: qualcuno se ne accorgerà.",
  "Il tuo collega ha una domanda veloce. Sta per invecchiarti.",
  "La carriera è una scala. Tu stai reggendo quella degli altri.",
  "Oggi farai squadra. Il merito farà un viaggio diverso dal tuo però.",
  "Il problema è urgente. Da tre settimane, ma te lo dicono adesso.",
  "Hai aperto il computer. La giornata ha smesso di appartenerti.",
  "«Ne parliamo domani». La minaccia più sottovalutata dell’ufficio.",
  "Se lavori bene, nessuno se ne accorge. Prova a sbagliare un allegato oggi e vedrai che tutti si ricorderanno di te.",
  "Il tuo premio produzione è sapere che potevi produrre di più.",
  "Il lavoro nobilita. Il saldo non conferma.",
  "«Siamo tutti sulla stessa barca». Tu intanto rema.",
  "La scadenza è flessibile. Puoi lavorarci anche stanotte.",
  "Hai preso un giorno libero di recente? lo ripagherai con gli interessi.",
  "Controlla il conto. Anche oggi una breve esperienza horror gratuita.",
  "I soldi non fanno la felicità. Le bollette ci provano ancora meno.",
  "Oggi concediti uno sfizio. Domani chiamalo errore.",
  "Hai risparmiato 20€. Amazon l’ha sentito. Domani ne spenderai 40.",
  "Sta arrivando una spesa imprevista. Ormai dovreste darvi del tu.",
  "Oggi è giusto che inizi la giornata investendo su te stesso. Con il budget che hai puoi permetterti un caffè.",
  "Hai guardato i prezzi delle case. Ora anche la tenda sembra un investimento.",
  "Il carrello è vuoto. Il conto pure. Almeno c’è coerenza.",
  "Il denaro va e viene. Il tuo ha preso solo l’andata.",
  "Risparmia per i giorni difficili. Ah, era oggi.",
  "Hai cancellato un abbonamento. Te ne restano quattro che non ricordi.",
  "Il portafoglio è leggero. Finalmente una zona del corpo in forma.",
  "Oggi senti un vuoto dentro. Potrebbe essere il mutuo appena pagato.",
  "La felicità non ha prezzo. Il resto ha pure le spese di spedizione.",
  "Il tuo piano finanziario è sperare che non si rompa niente.",
  "Arrivare a fine mese è facile. Il difficile è portarci anche i soldi.",
  "Hai messo soldi da parte. Il dentista sa da quale.",
  "Un piccolo acquisto non cambia nulla. Ne hai fatti diciannove.",
  "Lo stipendio è puntuale. Anche la sua sparizione.",
  "Goditi le cose gratis. Finché non introducono l’abbonamento.",
  "Ti meriti qualcuno che ti capisca. Preparati a essere insultato con precisione.",
  "Se son rose fioriranno. Per ora sembrano ortiche.",
  "Ti ha scritto «ciao». Calma, non prenotare il matrimonio.",
  "Oggi segui il cuore. Così la figura di merda avrà un movente.",
  "Il gruppo ha deciso quando vedersi. Scherzo, siete come al solito dei bifolchi",
  "Oggi qualcuno dirà «organizziamo». Non prendere impegni: non succederà.",
  "Stasera uscite tranquilli. Domani ricostruite i danni.",
  "La chat del gruppo è muta. Scrivi che offri tu stasera e guarda quanti conigli si palesano.",
  "I tuoi amici ti accettano come sei. Hanno abbassato le aspettative.",
  "«Bevo poco questa settimana». Anche questa settimana comincia con una menzogna.",
  "Hai detto un segreto. Bravo, ora sarà patrimonio del gruppo.",
  "L’amicizia non ha prezzo. Ma qualcuno deve ancora ridarti trenta euro.",
  "Tra di voi avete mille ricordi insieme. Per fortuna metà non li ricordate.",
  "Sei quello affidabile. Ti toccherà rompere i coglioni anche stavolta.",
  "Oggi farai ridere un amico. Probabilmente raccontandogli i tuoi fallimenti.",
  "I veri amici non giudicano. Conservano materiale.",
  "C’è sempre un cretino nel gruppo. Se non lo trovi, buona giornata.",
  "Oggi ti sentirai cercato. Qualcuno deve farsi prestare qualcosa.",
  "L’amico avventuroso propone. Quello con la macchina paga.",
  "Stasera sii te stesso e stattene a casa.",
  "Gli amici sono la famiglia che scegli. Hai ancora lo scontrino?",
  "Hai dormito male. Godo.",
  "Oggi il tuo corpo ti parlerà. Principalmente con scricchiolii.",
  "Il riposo ti ha fatto bene. Immagina come saresti senza.",
  "Hai fatto tardi per non fare niente. Disciplina impeccabile.",
  "La sveglia ha suonato. Anche oggi il primo torto è documentato.",
  "Oggi avrai energia da vendere. Il compratore non si presenterà.",
  "Dormire cinque minuti in più ti costerà quaranta minuti di panico.",
  "Oggi ascolta il tuo corpo. Ha già chiesto di tornare sotto le coperte.",
  "Hai l’età che ti senti. Stamattina serve una perizia archeologica.",
  "Un tempo recuperavi in una notte. Ora devi aprire una pratica.",
  "Il caffè ti tiene in piedi. Per la voglia di vivere serve altro.",
  "Hai dormito sul braccio. Anche lui sta cercando di lasciarti.",
  "Ieri ti alzavi e splendevi. Per ora ti alzi e imprechi.",
  "Lo specchio è stato onesto. Poteva almeno aspettare il caffè.",
  "Hai bisogno di una pausa. Dalla pausa che non ti ha riposato.",
  "La stanchezza passerà. Stasera alle undici, quando dovresti dormire.",
  "Oggi sei pieno di vita. Peccato sia tutta nelle occhiaie.",
  "Ti sei svegliato prima della sveglia. Una fregatura senza intermediari.",
  "Preparati al mal di schiena che arriverà tra qualche giorno.",
  "Oggi basta poco per farti felice. Otto ore senza che nessuno ti tocchi.",
  "La tua faccia dice tutto. Peccato durante le riunioni.",
  "Oggi parti al cento per cento. Di batteria scarica.",
  "Hai dormito nove ore. Evidentemente la stanchezza ha la residenza.",
  "La sveglia di domani è già impostata. La cattiveria richiede organizzazione.",
  "Oggi mangerai leggero. Il rimorso pesa comunque.",
  "Hai comprato l’insalata. Ora guardala morire mentre ordini una pizza.",
  "La dieta inizia lunedì.",
  "Un biscotto tira l’altro, stai attento.",
  "Il pranzo sano ti aspetta. Nel contenitore dimenticato a casa.",
  "Oggi concediti un peccato di gola. Ormai avete una relazione stabile.",
  "Hai comprato frutta per la settimana. Darai da mangiare ai moscerini.",
  "Ti alleni domani. Il divano ha vinto anche in trasferta.",
  "La palestra ti aspetta. Soprattutto il rinnovo automatico.",
  "Hai fatto diecimila passi. Novemila cercando parcheggio.",
  "Oggi supera i tuoi limiti. Quello della carta lo conosci già.",
  "Hai preparato la borsa da palestra. Un bel gesto simbolico.",
  "Hai corso cinque minuti. Il polmone ha chiesto un incontro.",
  "Oggi niente alcol. Lo hai già detto con tono negoziabile.",
  "«L’ultimo bicchiere». Nessuno ha specificato di quale bottiglia.",
  "Hai bevuto per dimenticare. Hai creato nuovi ricordi imbarazzanti.",
  "Il kebab delle tre sembrava un’idea geniale. L’intestino presenterà ricorso.",
  "Oggi bevi tanta acqua. Ormai sei vecchio.",
  "La bilancia non giudica. Si limita a rovinarti l’umore con precisione.",
  "Hai cucinato per risparmiare. Hai speso quaranta euro in spezie.",
  "Oggi mastica lentamente. La prossima rottura di coglioni può aspettare.",
  "Oggi internet cadrà nel momento giusto. Per rovinarti qualcosa.",
  "La password è sbagliata. Anche quella nuova sarà già stata usata.",
  "Hai aggiornato l’app. Quello che funzionava dava fastidio.",
  "La batteria è al due per cento. Finalmente qualcosa ti rappresenta.",
  "Oggi riceverai un messaggio importante. Tra quarantasette promozioni.",
  "Il telefono ti ascolta. Eppure nessuno ti capisce.",
  "Hai accettato i cookie. Almeno qualcuno sa cosa vuoi dalla vita.",
  "Hai salvato il file? La domanda arriva sempre dopo la tragedia.",
  "Oggi il computer farà esattamente quello che chiedi. Sarà colpa tua.",
  "Hai centotrenta schede aperte. Nessuna conterrà una soluzione.",
  "Il pacco arriva oggi. Passerà nei novanta secondi in cui sei al cesso.",
  "Hai cercato un sintomo online. Ora devi anche scegliere il marmo.",
  "Oggi smetti di confrontarti con gli altri. Dopo altre venti storie su instagram",
  "La tua vita privata è al sicuro. Non interessa nemmeno all’algoritmo.",
  "«Spazio esaurito». Anche il telefono ne ha abbastanza dei tuoi ricordi.",
  "Il riconoscimento facciale non ti riconosce. Stamattina ha delle ragioni.",
  "Hai silenziato il gruppo. La pace esisteva, costava tre tocchi.",
  "Oggi niente social. Ci rivediamo tra quattro minuti.",
  "Hai caricato una foto spontanea. Alla ventiseiesima prova.",
  "Hai dimenticato la password. Il sito non dimentica le tue sconfitte.",
  "Oggi il Wi-Fi prende ovunque. Tranne dove hai messo la sedia.",
  "Il tuo tempo sullo schermo è aumentato. Almeno qualcosa cresce.",
  "Hai inviato il messaggio alla persona sbagliata. Finalmente un po’ di trama.",
  "Il backup è automatico. L’unica cosa persa sarà quella importante.",
  "Oggi pulisci casa. La polvere ha già prenotato il ritorno.",
  "Il calzino sparito sta vivendo una vita migliore della tua.",
  "Oggi la vita ti darà ragione. Quando dirai che farà schifo.",
  "Ti sveglierai ottimista. Ti passerà appena incontrerai qualcuno.",
  "Oggi nessuno ti metterà i bastoni tra le ruote. Ti toglieranno direttamente le ruote.",
  "Farai un bel programma per oggi. La giornata se ne sbatterà il cazzo.",
  "Il destino ti chiuderà una porta. Ci lascerai le dita.",
  "Oggi raccoglierai quello che avrai seminato. Non ti servirà un cestino.",
  "Penserai di avere tutto sotto controllo. Poi ti aggiorneranno.",
  "Oggi qualcuno crederà in te. Ti chiederà di coprirgli il turno.",
  "Ti diranno «fai con calma». Due minuti dopo ti chiederanno se avrai finito.",
  "Oggi darai grandi soddisfazioni al lavoro. Le incasserà qualcun altro.",
  "Ti arriverà lo stipendio. Per qualche minuto ti sentirai perfino pagato.",
  "Oggi proverai a non spendere niente. Qualcosa in casa si romperà per principio.",
  "Ti scriveranno «dobbiamo parlare». Il resto della giornata lo passerai a cagarti sotto.",
  "Organizzerai una serata tra amici. Passerai il pomeriggio a inseguire otto adulti come una maestra in gita.",
  "Oggi partirai con una marcia in più. Finirai nel fosso più velocemente.",
  "Il caffè farà effetto tra poco. Farai le stesse cazzate, ma più velocemente.",
  "Sceglierai di prendere le scale. Al secondo piano rivaluterai tutta la tua vita.",
  "Oggi ti sentirai giovane. Poi ti alzerai dal divano.",
  "Troverai finalmente un momento per te. Ti chiameranno esattamente allora.",
  "Oggi arriverà finalmente una gioia. Ti chiederanno di consegnarla al vicino.",
  "Oggi incontrerai un problema così inutile che avrà sicuramente la massima urgenza.",
  "Oggi incontrerai una persona convinta che il tuo tempo le appartenga per diritto divino.",
  "Oggi incontrerai una spesa che trasformerà il tuo saldo in un necrologio.",
  "Oggi incontrerai un imprevisto che aveva già prenotato il posto prima della tua sveglia.",
  "Oggi incontrerai una decisione semplice, subito migliorata da dodici opinioni non richieste.",
  "Oggi incontrerai un messaggio che inizierà con «non preoccuparti» e finirà esattamente al contrario.",
  "Oggi incontrerai un’occasione perfetta per chiederti perché non sei rimasto a letto.",
  "Oggi incontrerai una piccola vittoria che qualcun altro riuscirà a intestarsi.",
  "Oggi incontrerai un nuovo limite personale, quasi certamente verso il basso.",
  "Oggi incontrerai la conferma che le aspettative basse erano ancora troppo ottimiste.",
  "Prima di sera ti capiterà un problema così inutile che avrà sicuramente la massima urgenza.",
  "Prima di sera ti capiterà una persona convinta che il tuo tempo le appartenga per diritto divino.",
  "Prima di sera ti capiterà una spesa che trasformerà il tuo saldo in un necrologio.",
  "Prima di sera ti capiterà un imprevisto che aveva già prenotato il posto prima della tua sveglia.",
  "Prima di sera ti capiterà una decisione semplice, subito migliorata da dodici opinioni non richieste.",
  "Prima di sera ti capiterà un messaggio che inizierà con «non preoccuparti» e finirà esattamente al contrario.",
  "Prima di sera ti capiterà un’occasione perfetta per chiederti perché non sei rimasto a letto.",
  "Prima di sera ti capiterà una piccola vittoria che qualcun altro riuscirà a intestarsi.",
  "Prima di sera ti capiterà un nuovo limite personale, quasi certamente verso il basso.",
  "Prima di sera ti capiterà la conferma che le aspettative basse erano ancora troppo ottimiste.",
  "La giornata ti servirà un problema così inutile che avrà sicuramente la massima urgenza.",
  "La giornata ti servirà una persona convinta che il tuo tempo le appartenga per diritto divino.",
  "La giornata ti servirà una spesa che trasformerà il tuo saldo in un necrologio.",
  "La giornata ti servirà un imprevisto che aveva già prenotato il posto prima della tua sveglia.",
  "La giornata ti servirà una decisione semplice, subito migliorata da dodici opinioni non richieste.",
  "La giornata ti servirà un messaggio che inizierà con «non preoccuparti» e finirà esattamente al contrario.",
  "La giornata ti servirà un’occasione perfetta per chiederti perché non sei rimasto a letto.",
  "La giornata ti servirà una piccola vittoria che qualcun altro riuscirà a intestarsi.",
  "La giornata ti servirà un nuovo limite personale, quasi certamente verso il basso.",
  "La giornata ti servirà la conferma che le aspettative basse erano ancora troppo ottimiste.",
  "Il destino ti consegnerà un problema così inutile che avrà sicuramente la massima urgenza.",
  "Il destino ti consegnerà una persona convinta che il tuo tempo le appartenga per diritto divino.",
  "Il destino ti consegnerà una spesa che trasformerà il tuo saldo in un necrologio.",
  "Il destino ti consegnerà un imprevisto che aveva già prenotato il posto prima della tua sveglia.",
  "Il destino ti consegnerà una decisione semplice, subito migliorata da dodici opinioni non richieste.",
  "Il destino ti consegnerà un messaggio che inizierà con «non preoccuparti» e finirà esattamente al contrario.",
  "Il destino ti consegnerà un’occasione perfetta per chiederti perché non sei rimasto a letto.",
  "Il destino ti consegnerà una piccola vittoria che qualcun altro riuscirà a intestarsi.",
  "Il destino ti consegnerà un nuovo limite personale, quasi certamente verso il basso.",
  "Il destino ti consegnerà la conferma che le aspettative basse erano ancora troppo ottimiste.",
  "Quando penserai di essere tranquillo arriverà un problema così inutile che avrà sicuramente la massima urgenza.",
  "Quando penserai di essere tranquillo arriverà una persona convinta che il tuo tempo le appartenga per diritto divino.",
  "Quando penserai di essere tranquillo arriverà una spesa che trasformerà il tuo saldo in un necrologio.",
  "Quando penserai di essere tranquillo arriverà un imprevisto che aveva già prenotato il posto prima della tua sveglia.",
  "Quando penserai di essere tranquillo arriverà una decisione semplice, subito migliorata da dodici opinioni non richieste.",
  "Quando penserai di essere tranquillo arriverà un messaggio che inizierà con «non preoccuparti» e finirà esattamente al contrario.",
  "Quando penserai di essere tranquillo arriverà un’occasione perfetta per chiederti perché non sei rimasto a letto.",
  "Quando penserai di essere tranquillo arriverà una piccola vittoria che qualcun altro riuscirà a intestarsi.",
  "Quando penserai di essere tranquillo arriverà un nuovo limite personale, quasi certamente verso il basso.",
  "Quando penserai di essere tranquillo arriverà la conferma che le aspettative basse erano ancora troppo ottimiste.",
  "Oggi dovrai gestire un problema così inutile che avrà sicuramente la massima urgenza.",
  "Oggi dovrai gestire una persona convinta che il tuo tempo le appartenga per diritto divino.",
  "Oggi dovrai gestire una spesa che trasformerà il tuo saldo in un necrologio.",
  "Oggi dovrai gestire un imprevisto che aveva già prenotato il posto prima della tua sveglia.",
  "Oggi dovrai gestire una decisione semplice, subito migliorata da dodici opinioni non richieste.",
  "Oggi dovrai gestire un messaggio che inizierà con «non preoccuparti» e finirà esattamente al contrario.",
  "Oggi dovrai gestire un’occasione perfetta per chiederti perché non sei rimasto a letto.",
  "Oggi dovrai gestire una piccola vittoria che qualcun altro riuscirà a intestarsi.",
  "Oggi dovrai gestire un nuovo limite personale, quasi certamente verso il basso.",
  "Oggi dovrai gestire la conferma che le aspettative basse erano ancora troppo ottimiste.",
  "La vita metterà sul tuo cammino un problema così inutile che avrà sicuramente la massima urgenza.",
  "La vita metterà sul tuo cammino una persona convinta che il tuo tempo le appartenga per diritto divino.",
  "La vita metterà sul tuo cammino una spesa che trasformerà il tuo saldo in un necrologio.",
  "La vita metterà sul tuo cammino un imprevisto che aveva già prenotato il posto prima della tua sveglia.",
  "La vita metterà sul tuo cammino una decisione semplice, subito migliorata da dodici opinioni non richieste.",
  "La vita metterà sul tuo cammino un messaggio che inizierà con «non preoccuparti» e finirà esattamente al contrario.",
  "La vita metterà sul tuo cammino un’occasione perfetta per chiederti perché non sei rimasto a letto.",
  "La vita metterà sul tuo cammino una piccola vittoria che qualcun altro riuscirà a intestarsi.",
  "La vita metterà sul tuo cammino un nuovo limite personale, quasi certamente verso il basso.",
  "La vita metterà sul tuo cammino la conferma che le aspettative basse erano ancora troppo ottimiste.",
  "Entro stasera scoprirai un problema così inutile che avrà sicuramente la massima urgenza.",
  "Entro stasera scoprirai una persona convinta che il tuo tempo le appartenga per diritto divino.",
  "Entro stasera scoprirai una spesa che trasformerà il tuo saldo in un necrologio.",
  "Entro stasera scoprirai un imprevisto che aveva già prenotato il posto prima della tua sveglia.",
  "Entro stasera scoprirai una decisione semplice, subito migliorata da dodici opinioni non richieste.",
  "Entro stasera scoprirai un messaggio che inizierà con «non preoccuparti» e finirà esattamente al contrario.",
  "Entro stasera scoprirai un’occasione perfetta per chiederti perché non sei rimasto a letto.",
  "Entro stasera scoprirai una piccola vittoria che qualcun altro riuscirà a intestarsi.",
  "Entro stasera scoprirai un nuovo limite personale, quasi certamente verso il basso.",
  "Entro stasera scoprirai la conferma che le aspettative basse erano ancora troppo ottimiste.",
  "Il tuo ottimismo attirerà un problema così inutile che avrà sicuramente la massima urgenza.",
  "Il tuo ottimismo attirerà una persona convinta che il tuo tempo le appartenga per diritto divino.",
  "Il tuo ottimismo attirerà una spesa che trasformerà il tuo saldo in un necrologio.",
  "Il tuo ottimismo attirerà un imprevisto che aveva già prenotato il posto prima della tua sveglia.",
  "Il tuo ottimismo attirerà una decisione semplice, subito migliorata da dodici opinioni non richieste.",
  "Il tuo ottimismo attirerà un messaggio che inizierà con «non preoccuparti» e finirà esattamente al contrario.",
  "Il tuo ottimismo attirerà un’occasione perfetta per chiederti perché non sei rimasto a letto.",
  "Il tuo ottimismo attirerà una piccola vittoria che qualcun altro riuscirà a intestarsi.",
  "Il tuo ottimismo attirerà un nuovo limite personale, quasi certamente verso il basso.",
  "Il tuo ottimismo attirerà la conferma che le aspettative basse erano ancora troppo ottimiste.",
  "La tua proverbiale fortuna produrrà un problema così inutile che avrà sicuramente la massima urgenza.",
  "La tua proverbiale fortuna produrrà una persona convinta che il tuo tempo le appartenga per diritto divino.",
  "La tua proverbiale fortuna produrrà una spesa che trasformerà il tuo saldo in un necrologio.",
  "La tua proverbiale fortuna produrrà un imprevisto che aveva già prenotato il posto prima della tua sveglia.",
  "La tua proverbiale fortuna produrrà una decisione semplice, subito migliorata da dodici opinioni non richieste.",
  "La tua proverbiale fortuna produrrà un messaggio che inizierà con «non preoccuparti» e finirà esattamente al contrario.",
  "La tua proverbiale fortuna produrrà un’occasione perfetta per chiederti perché non sei rimasto a letto.",
  "La tua proverbiale fortuna produrrà una piccola vittoria che qualcun altro riuscirà a intestarsi.",
  "La tua proverbiale fortuna produrrà un nuovo limite personale, quasi certamente verso il basso.",
  "La tua proverbiale fortuna produrrà la conferma che le aspettative basse erano ancora troppo ottimiste."
] as const;

const NEWS_712_BASE_MESSAGES = [
  "Su Terra 712 Lola è stato eletto sindaco dopo aver promesso di non occuparsi di nulla. A tre mesi dall’insediamento è l’unico politico ad aver rispettato l’intero programma.",
  "Roger ha acquistato un terreno nel metaverso e ci ha trovato Tappo che coltivava zucchine. La controversia è ora al vaglio di un geometra virtuale.",
  "Bugs è stato assunto dalla NASA per verificare se nello spazio si sente il rumore di una busta di patatine. La missione ha già subito sei pause.",
  "Tippete ha denunciato il proprio sosia per furto d’identità. Gli investigatori hanno scoperto che il sosia conduce una vita migliore e gli hanno consigliato di lasciarlo fare.",
  "Quick ha stabilito il record mondiale dei cento metri durante una fuga dal cameriere. Il primato non sarà omologato finché non salda il conto.",
  "Palla di Neve è stato nominato responsabile del riscaldamento globale. «Il nome non deve ingannare», ha precisato il governo.",
  "Tappo ha aperto un ristorante senza tavoli per contrastare il calo delle prenotazioni. Il locale risulta già completo fino a novembre.",
  "Bianconiglio ha chiesto il divorzio dalla propria versione del futuro. Alla base della separazione, fatti che devono ancora accadere.",
  "Lola ha ereditato una rotatoria da uno zio sconosciuto. Da lunedì sarà necessario citofonare per prendere la terza uscita.",
  "Roger è rimasto bloccato per nove ore in una porta automatica dopo aver dichiarato di non sapere se entrare. Sul posto è intervenuto un mediatore.",
  "Bugs ha fondato una compagnia aerea che parte soltanto quando tutti hanno davvero voglia. Il primo volo è stato rimandato a dopo le feste.",
  "Tippete è diventato il primo uomo a ottenere la residenza in una sala d’attesa. L’ASL gli ha già inviato le spese condominiali.",
  "Quick ha conseguito la patente per astronavi, ma può guidare soltanto se accompagnato da un adulto sobrio. Al momento non è riuscito a partire.",
  "Palla di Neve ha comprato una montagna pensando fosse edificabile. Il venditore gli avrebbe mostrato soltanto la cima.",
  "Tappo ha depositato il brevetto di una sedia che si allontana quando qualcuno dice «ti rubo solo un minuto». Il Parlamento ne ha ordinati seicento esemplari.",
  "Bianconiglio è stato multato per aver parcheggiato ieri in una zona che diventerà pedonale domani. Ha annunciato ricorso la settimana scorsa.",
  "Lola è stato espulso da un corso di meditazione per aver raggiunto la pace interiore prima dell’insegnante e aver iniziato a dargli consigli.",
  "Roger ha aperto un conto in una banca del tempo. È già sotto di quattro martedì.",
  "Bugs è stato nominato ambasciatore presso una civiltà aliena dopo aver risposto «anche a te» al loro ultimatum. I rapporti sono definiti ottimi.",
  "Tippete ha trovato un passaggio segreto dietro il frigorifero. Conduce a un altro supermercato, leggermente più caro.",
  "Quick ha vinto una maratona restando a casa. Gli organizzatori ammettono che il percorso ad anello presentava alcune criticità.",
  "Palla di Neve ha chiesto un finanziamento per aprire un vulcano in franchising. Il comune attende chiarimenti sulla canna fumaria.",
  "Tappo è stato assolto dall’accusa di aver rubato il silenzio. Decisiva l’assenza di testimonianze.",
  "Bianconiglio ha ricevuto una cartella esattoriale per un’esistenza precedente. Contesta soprattutto gli interessi maturati durante il Medioevo.",
  "Lola ha acquistato il trenta per cento della Luna. Per il momento gli spettano due crateri e il giovedì.",
  "Roger ha presentato un’app che permette di saltare le conversazioni e arrivare direttamente al litigio. Raccolti dodici milioni nel primo round.",
  "Bugs è stato ricoverato dopo aver preso alla lettera il consiglio di mettersi nei panni degli altri. I pantaloni appartenevano a un bambino.",
  "Tippete è diventato amministratore di un condominio abitato soltanto da sue copie. Sono già in corso undici cause civili.",
  "Quick ha superato la velocità della luce per arrivare puntuale a cena. Gli altri hanno scritto che stanno ancora facendo la doccia.",
  "Palla di Neve ha aperto uno stabilimento balneare su Marte. I clienti apprezzano la tranquillità, ma segnalano la distanza dall’acqua.",
  "Tappo è stato fermato alla dogana con diciotto chili di atmosfera non dichiarata. Sostiene fosse aria di casa.",
  "Bianconiglio ha assunto un assistente incaricato di ricordargli perché è entrato nelle stanze. Il posto prevede trasferte frequenti in cucina.",
  "Lola ha vinto un processo contro il proprio navigatore. Il tribunale ha stabilito che «sei arrivato» non fosse una descrizione accettabile del fosso.",
  "Roger è stato eletto presidente dell’associazione degli indecisi. Non ha ancora accettato, ma non intende rinunciare.",
  "Bugs ha avviato un allevamento di piccioni viaggiatori specializzati in raccomandate. Gli animali lasciano l’avviso anche quando il destinatario è in casa.",
  "Tippete ha ordinato una personalità nuova su internet. Il pacco contiene la stessa, ma con maggiore sicurezza.",
  "Quick è diventato il primo corriere a consegnare un pacco prima dell’acquisto. Il destinatario sta valutando se gli piace.",
  "Palla di Neve ha brevettato la neve tiepida. Le prime applicazioni riguardano gli anziani che vogliono sciare senza prendere freddo.",
  "Tappo ha acquistato un castello infestato e messo i fantasmi a contratto. La struttura offre ora animazione anche nei mesi invernali.",
  "Bianconiglio ha prenotato una vacanza nel passato. Al rientro ha lasciato una recensione negativa per l’assenza di prese vicino al letto.",
  "Lola è stato nominato ministro delle cose lasciate a metà. La cerimonia di insediamento proseguirà appena trova un momento.",
  "Roger ha denunciato un ristorante per avergli servito un piatto della tradizione inventata quella mattina. Lo chef sostiene che da qualche parte bisogna cominciare.",
  "Bugs ha aperto una palestra dove i personal trainer fanno gli esercizi al posto dei clienti. Gli abbonamenti annuali sono esauriti.",
  "Tippete ha ricevuto per errore il premio Nobel per la fisica. Ha chiesto se fosse possibile cambiarlo con quello per la pace, più adatto al soggiorno.",
  "Quick ha accettato un impiego come pendolare interdimensionale. Il tragitto dura otto secondi, ma il raccordo aggiunge un’ora e mezza.",
  "Palla di Neve ha scoperto una nuova specie marina durante un bagno. L’animale ha chiesto di non essere associato pubblicamente all’episodio.",
  "Tappo ha chiesto al comune di spostare il tramonto perché gli batte sul televisore. La proposta è all’esame della commissione paesaggio.",
  "Bianconiglio ha messo in vendita il proprio futuro. Diversi interessati hanno rinunciato dopo aver visionato il lunedì.",
  "Lola è diventato re di una piccola isola dopo aver portato una multipresa. Il precedente sovrano disponeva soltanto di un adattatore.",
  "Roger ha aperto un ufficio reclami dedicato ai sogni. Le segnalazioni riguardano soprattutto denti, ex e nudità sul luogo di lavoro.",
  "Bugs ha costruito un robot identico a lui per partecipare alle cene. Il robot ha iniziato a inventare scuse.",
  "Tippete è stato arrestato per aver contraffatto buoni propositi. Li vendeva già realizzati.",
  "Quick ha vinto una gara di pazienza in meno di quattro minuti. La giuria sta cercando di capire come.",
  "Palla di Neve è diventato proprietario di un iceberg. Lo tiene in garage in attesa che aumenti di valore.",
  "Tappo ha introdotto il coperto nelle cene a casa propria. Gli amici contestano soprattutto i due euro per il pane che hanno portato loro.",
  "Bianconiglio ha smarrito tre ore durante un cambio di fuso. Sono state ritrovate da Roger, che le aveva già impegnate.",
  "Lola ha inaugurato un museo dedicato alle cose che avrebbe potuto fare. L’ala principale è ancora in progettazione.",
  "Roger ha ricevuto una multa per eccesso di confidenza con un pubblico ufficiale. Avrebbe chiamato il prefetto «bomber» in sette occasioni.",
  "Bugs è stato convocato da una commissione scientifica dopo aver fatto funzionare una stampante dicendole di smetterla. Il metodo non è ancora riproducibile.",
  "Tippete ha aperto un vivaio di piante finte. Il primo raccolto è stato compromesso da un problema alla plastica.",
  "Quick ha prenotato un tavolo per otto in otto ristoranti diversi. Sostiene che nel gruppo nessuno avesse espresso una preferenza chiara.",
  "Palla di Neve ha vinto un soggiorno in un universo parallelo. Ha chiesto il rimborso perché c’era comunque Roger.",
  "Tappo è stato nominato garante della quiete pubblica dopo aver staccato la cassa durante una festa. La nomina resta molto discussa tra i presenti.",
  "Bianconiglio ha trovato lavoro come testimone di eventi futuri. Il tribunale gli chiede di non anticipare il finale durante le deposizioni.",
  "Lola ha fatto installare un casello davanti al bagno di casa. I residenti avranno diritto a venti transiti gratuiti al mese.",
  "Roger ha lanciato una criptovaluta garantita da promesse fatte al bar. Il valore è crollato dopo che qualcuno ha chiesto di essere pagato davvero.",
  "Bugs ha trascorso sei mesi sotto copertura in un gruppo di calcetto. L’operazione non ha prodotto risultati, ma giovedì manca ancora uno.",
  "Tippete ha ottenuto un risarcimento per una vacanza troppo rilassante. Al rientro non riusciva più a fingere interesse per il proprio lavoro.",
  "Quick ha inventato un ascensore che porta direttamente al motivo per cui eri salito. Il modello base arriva fino alle chiavi.",
  "Palla di Neve ha candidato il proprio divano a patrimonio dell’umanità. L’UNESCO chiede accesso al lato coperto dai vestiti.",
  "Tappo ha aperto una banca che conserva gli avanzi. I tortellini fruttano il quattro per cento annuo.",
  "Bianconiglio ha perso una causa contro se stesso del 2038. Il suo avvocato ritiene che la controparte disponesse di informazioni privilegiate."
] as const;

export const NEWS_712_MESSAGES = [
  ...NEWS_712_BASE_MESSAGES,
  ...NEWS_712_ADDITIONAL_MESSAGES,
] as const;
